#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

ARG BASE_IMAGE="docker.io/php:8.1.1-cli"

FROM docker.io/php@sha256:8f62dbb3ab718cfb3ab83a30a042ac4000def040a1ccba04a188f3ad884b8d59

#{INCLUDE:../base.dockerfile}
